openapi: 3.0.0
info:
  title: businessservice
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /business/new:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-business-new
      security:
        - openIDOne: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessForm'
  '/business/{ID}':
    parameters:
      - schema:
          type: string
        name: ID
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Business'
      operationId: get-business-ID
components:
  schemas:
    Business:
      title: Business
      type: object
      properties:
        id:
          type: string
        userIDs:
          type: array
          items:
            type: string
    BusinessSettings:
      title: BusinessSettings
      type: object
      properties:
        id:
          type: string
    BusinessForm:
      title: BusinessForm
      type: object
      properties:
        userIDs:
          type: array
          items:
            type: string
  securitySchemes:
    openIDOne:
      type: openIdConnect
