openapi: 3.0.0
info:
  title: trackingservice
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tracking/new:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      operationId: get-tracking-new
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
components:
  schemas:
    Track:
      title: Track
      type: object
      properties:
        id:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        timestamp:
          type: string
          format: date-time
        vehicleID:
          type: string
        businessID:
          type: string
    Location:
      title: Location
      type: object
      properties:
        lon:
          type: number
        lat:
          type: number
        alt:
          type: number
      description: ''
    TrackForm:
      title: TrackForm
      type: object
      properties:
        location:
          $ref: '#/components/schemas/Location'
  securitySchemes: {}
